server:
  port: 8888

spring:
  application:
    name: config

  cloud:
    config:
      server:
        git:
          uri: git@github.com:jinkyumpark/booksitout-config.git
          ignoreLocalSshSettings: true
          privateKey: ${SSH_PRIVATE_KEY}

eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/