server:
  port: 80

jwt:
  secret: ${JWT_SECRET}

spring:
  application:
    name: gateway

  eureka:
      client:
          service-url:
            default-zone: http://localhost:8761/eureka/

  cloud:
    gateway:
      discovery:
        locator:
            enabled: true

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000, https://booksitout.com"
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS

      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**

        - id: search
          uri: lb://search
          predicates:
            - Path=/v2/search/**, /v3/search/**
          filters:
            - JwtValidationFilter

        - id: core
          uri: lb://core
          predicates:
            - Path=/v1/**, /v2/**, /v3/**
          filters:
            - JwtValidationFilter