server:
  port: 80

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000, https://book.jinkyumpark.com"
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS

      routes:
        - id: user
          uri: http://localhost:8000
          predicates:
            - Path=/login, {segment}/login/**, {segment}/join

        - id: search
          uri: http://localhost:8100
          predicates:
            - Path=/v2/search/**

        - id: core
          uri: http://localhost:8000
          predicates:
            - Path=/v1/**, /v2/**
