server:
  port: 80

jwt:
  secret: ${JWT_SECRET}

eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          polling-interval: 1

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS

      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**, /{version}/login/**

        - id: search-login
          uri: lib://search
          predicates:
            - Path=/{version}/search/library/settings/**, /{version}/settings/**
          filters:
            - JwtValidationFilter

        - id: search
          uri: lb://search
          predicates:
            - Path=/{version}/search/**

        - id: core
          uri: lb://core
          predicates:
            - Path=/{version}/**
          filters:
            - JwtValidationFilter