server:
  port: 80

spring:
  application:
    name: spring-gateway

  eureka:
      client:
          service-url:
            default-zone: http://localhost:8761/eureka/

  cloud:
    gateway:
      discovery:
        locator:
            enabled: true

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000, https://book.jinkyumpark.com"
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS

      routes:
        - id: user
          uri: lb://core
          predicates:
            - Path=/login, {segment}/login/**, {segment}/join, v3/user/**, v2/login/**

        - id: search
          uri: lb://search
          predicates:
            - Path=/v2/search/**

        - id: core
          uri: lb://core
          predicates:
            - Path=/v1/**, /v2/**