server:
    port: 0

spring:
    application:
        name: search

    redis:
        pool:
            min-idle: 0
            max-idle: 8
            max-active: 8

        port: 6379
        host: localhost

    datasource:
        url: jdbc:mysql://localhost:3306/search
        username: root
        password: bookitout

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format-sql: true

search:
    aladin:
        url: http://www.aladin.co.kr/ttb/api/ItemSearch.aspx
        secret: ${ALADIN_SECRET}

    data4library:
        url:
            has-book: http://data4library.kr/api/bookExist
            has-book-by-isbn: http://data4library.kr/api/libSrchByBook
            search: http://data4library.kr/api/srchBooks
            supported-library-url: http://data4library.kr/api/libSrch
        secret: ${DATA4LIBRARY_SECRET}

    kyobo:
        url: https://search.kyobobook.co.kr/search

    yes24:
        url: http://www.yes24.com/Product/Search

    naver:
        url: https://openapi.naver.com/v1/search/book.json
        secret: ${NAVER_SECRET}
        clientId: ${NAVER_CLIENT}

    google:
        url: https://customsearch.googleapis.com/customsearch/v1
        secret: ${GOOGLE_SECRET}
        cx: ${GOOGLE_CX}

eureka:
    instance:
        prefer-ip-address: true

    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
          default-zone: http://localhost:8761/eureka/